local M = {}

function M.get(c, _)
  return {
    -- Telescope
    TelescopeNormal          = { fg = c.fg, bg = c.bg_dim },
    TelescopeBorder          = { fg = c.border, bg = c.bg_dim },
    TelescopeTitle           = { fg = c.yellow, bold = true },
    TelescopePromptNormal    = { fg = c.fg, bg = c.bg_light },
    TelescopePromptBorder    = { fg = c.border, bg = c.bg_light },
    TelescopePromptTitle     = { fg = c.yellow, bg = c.bg_light, bold = true },
    TelescopePromptPrefix    = { fg = c.orange },
    TelescopePromptCounter   = { fg = c.fg_dim },
    TelescopeResultsNormal   = { fg = c.fg, bg = c.bg_dim },
    TelescopeResultsBorder   = { fg = c.border, bg = c.bg_dim },
    TelescopeResultsTitle    = { fg = c.fg_dim, bg = c.bg_dim },
    TelescopePreviewNormal   = { fg = c.fg, bg = c.bg },
    TelescopePreviewBorder   = { fg = c.border, bg = c.bg },
    TelescopePreviewTitle    = { fg = c.teal, bg = c.bg, bold = true },
    TelescopeSelection       = { bg = c.selection },
    TelescopeSelectionCaret  = { fg = c.orange, bg = c.selection },
    TelescopeMatching        = { fg = c.yellow, bold = true },

    -- nvim-tree
    NvimTreeNormal           = { fg = c.fg, bg = c.bg_dim },
    NvimTreeNormalNC         = { fg = c.fg_dim, bg = c.bg_dim },
    NvimTreeWinSeparator     = { fg = c.border, bg = c.bg_dim },
    NvimTreeCursorLine       = { bg = c.selection },
    NvimTreeRootFolder       = { fg = c.orange, bold = true },
    NvimTreeFolderName       = { fg = c.blue },
    NvimTreeFolderIcon       = { fg = c.blue },
    NvimTreeOpenedFolderName = { fg = c.blue, bold = true },
    NvimTreeEmptyFolderName  = { fg = c.fg_dim },
    NvimTreeFileName         = { fg = c.fg },
    NvimTreeExecFile         = { fg = c.green, bold = true },
    NvimTreeGitNew           = { fg = c.green },
    NvimTreeGitDirty         = { fg = c.orange },
    NvimTreeGitDeleted       = { fg = c.red },
    NvimTreeGitStaged        = { fg = c.teal },
    NvimTreeSymlink          = { fg = c.teal },
    NvimTreeIndentMarker     = { fg = c.border },

    -- neo-tree
    NeoTreeNormal            = { fg = c.fg, bg = c.bg_dim },
    NeoTreeNormalNC          = { fg = c.fg_dim, bg = c.bg_dim },
    NeoTreeCursorLine        = { bg = c.selection },
    NeoTreeRootName          = { fg = c.orange, bold = true },
    NeoTreeDirectoryName     = { fg = c.blue },
    NeoTreeDirectoryIcon     = { fg = c.blue },
    NeoTreeFileName          = { fg = c.fg },
    NeoTreeGitAdded          = { fg = c.green },
    NeoTreeGitModified       = { fg = c.orange },
    NeoTreeGitDeleted        = { fg = c.red },
    NeoTreeIndentMarker      = { fg = c.border },
    NeoTreeFloatBorder       = { fg = c.border },
    NeoTreeTitleBar          = { fg = c.yellow, bold = true },

    -- gitsigns
    GitSignsAdd              = { fg = c.green },
    GitSignsChange           = { fg = c.orange },
    GitSignsDelete           = { fg = c.red },
    GitSignsAddNr            = { fg = c.green },
    GitSignsChangeNr         = { fg = c.orange },
    GitSignsDeleteNr         = { fg = c.red },
    GitSignsAddLn            = { bg = c.diff_add },
    GitSignsChangeLn         = { bg = c.diff_change },
    GitSignsDeleteLn         = { bg = c.diff_delete },
    GitSignsCurrentLineBlame = { fg = c.fg_dim, italic = true },

    -- nvim-cmp
    CmpItemAbbr              = { fg = c.fg },
    CmpItemAbbrDeprecated    = { fg = c.fg_dim, strikethrough = true },
    CmpItemAbbrMatch         = { fg = c.yellow, bold = true },
    CmpItemAbbrMatchFuzzy    = { fg = c.yellow },
    CmpItemKind              = { fg = c.teal },
    CmpItemMenu              = { fg = c.fg_dim, italic = true },
    CmpItemKindText          = { fg = c.fg },
    CmpItemKindMethod        = { fg = c.blue },
    CmpItemKindFunction      = { fg = c.blue },
    CmpItemKindConstructor   = { fg = c.blue },
    CmpItemKindField         = { fg = c.fg },
    CmpItemKindVariable      = { fg = c.fg },
    CmpItemKindClass         = { fg = c.teal },
    CmpItemKindInterface     = { fg = c.teal },
    CmpItemKindModule        = { fg = c.teal },
    CmpItemKindProperty      = { fg = c.fg },
    CmpItemKindKeyword       = { fg = c.violet },
    CmpItemKindSnippet       = { fg = c.orange },
    CmpItemKindColor         = { fg = c.yellow },
    CmpItemKindFile          = { fg = c.blue },
    CmpItemKindFolder        = { fg = c.blue },
    CmpItemKindEnumMember    = { fg = c.yellow },
    CmpItemKindConstant      = { fg = c.yellow },
    CmpItemKindStruct        = { fg = c.teal },
    CmpItemKindTypeParameter = { fg = c.teal },

    -- which-key
    WhichKey               = { fg = c.yellow },
    WhichKeyGroup          = { fg = c.blue },
    WhichKeyDesc           = { fg = c.fg },
    WhichKeySeparator      = { fg = c.fg_dim },
    WhichKeyFloat          = { bg = c.bg_dim },
    WhichKeyBorder         = { fg = c.border },
    WhichKeyValue          = { fg = c.fg_dim },

    -- indent-blankline
    IblIndent              = { fg = c.border },
    IblScope               = { fg = c.fg_dim },
    IblWhitespace          = { fg = c.border },

    -- mini.nvim (共通)
    MiniIndentscopeSymbol  = { fg = c.fg_dim },
    MiniCursorword         = { underline = true },
    MiniStatuslineFilename = { fg = c.fg, bg = c.bg_dim },
    MiniStatuslineFileinfo = { fg = c.fg_dim, bg = c.bg_dim },
    MiniStatuslineModeNormal  = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeInsert  = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeVisual  = { fg = c.bg, bg = c.violet, bold = true },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.orange, bold = true },
    MiniStatuslineModeOther   = { fg = c.bg, bg = c.teal, bold = true },

    -- dropbar.nvim
    DropBarCurrentContext      = { bg = c.selection },
    DropBarCurrentContextIcon  = { fg = c.yellow, bg = c.selection },
    DropBarCurrentContextName  = { fg = c.fg, bg = c.selection, bold = true },
    DropBarFzfMatch            = { fg = c.yellow, bold = true },
    DropBarHover               = { bg = c.selection },
    DropBarIconKindDefault     = { fg = c.teal },
    DropBarIconKindDefaultNC   = { fg = c.fg_dim },
    DropBarIconUIIndicator     = { fg = c.orange },
    DropBarIconUIPickPivot     = { fg = c.red, bold = true },
    DropBarIconUISeparator     = { fg = c.border },
    DropBarIconUISeparatorMenu = { fg = c.border },
    DropBarMenuCurrentContext  = { bg = c.selection },
    DropBarMenuFloatBorder     = { fg = c.border, bg = c.bg_dim },
    DropBarMenuHoverEntry      = { bg = c.bg_light },
    DropBarMenuHoverIcon       = { reverse = true },
    DropBarMenuHoverSymbol     = { bold = true },
    DropBarMenuNormalFloat     = { fg = c.fg, bg = c.bg_dim },
    DropBarMenuSbar            = { bg = c.bg_light },
    DropBarMenuThumb           = { bg = c.fg_dim },
    DropBarPreview             = { bg = c.selection },
    DropBarKindFile            = { fg = c.fg },
    DropBarKindFolder          = { fg = c.blue },
    DropBarKindModule          = { fg = c.teal },
    DropBarKindNamespace       = { fg = c.teal },
    DropBarKindPackage         = { fg = c.orange },
    DropBarKindClass           = { fg = c.teal },
    DropBarKindMethod          = { fg = c.blue },
    DropBarKindProperty        = { fg = c.fg },
    DropBarKindField           = { fg = c.fg },
    DropBarKindConstructor     = { fg = c.blue },
    DropBarKindEnum            = { fg = c.yellow },
    DropBarKindInterface       = { fg = c.teal },
    DropBarKindFunction        = { fg = c.blue },
    DropBarKindVariable        = { fg = c.fg },
    DropBarKindConstant        = { fg = c.yellow },
    DropBarKindString          = { fg = c.green },
    DropBarKindNumber          = { fg = c.orange },
    DropBarKindBoolean         = { fg = c.orange },
    DropBarKindArray           = { fg = c.violet },
    DropBarKindObject          = { fg = c.violet },
    DropBarKindKey             = { fg = c.yellow },
    DropBarKindNull            = { fg = c.fg_dim },
    DropBarKindEnumMember      = { fg = c.yellow },
    DropBarKindStruct          = { fg = c.teal },
    DropBarKindEvent           = { fg = c.orange },
    DropBarKindOperator        = { fg = c.fg },
    DropBarKindTypeParameter   = { fg = c.teal },

    -- snacks.nvim
    SnacksPickerFile                = { fg = c.fg },
    SnacksPickerDirectory           = { fg = c.blue },
    SnacksPickerDir                 = { fg = c.fg_dim },
    SnacksPickerTree                = { fg = c.border },
    SnacksPickerMatch               = { fg = c.yellow, bold = true },
    SnacksPickerSearch              = { fg = c.bg, bg = c.yellow },
    SnacksPickerPathIgnored         = { fg = c.fg_dim },
    SnacksPickerPathHidden          = { fg = c.fg_dim },
    SnacksPickerGitStatusAdded      = { fg = c.green },
    SnacksPickerGitStatusModified   = { fg = c.orange },
    SnacksPickerGitStatusDeleted    = { fg = c.red },
    SnacksPickerGitStatusRenamed    = { fg = c.orange },
    SnacksPickerGitStatusUntracked  = { fg = c.fg_dim },
    SnacksPickerGitStatusIgnored    = { fg = c.fg_dim },
    SnacksPickerGitStatusUnmerged   = { fg = c.red },
    SnacksPickerGitStatusStaged     = { fg = c.teal },

    -- blink.cmp
    BlinkCmpMenu              = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpMenuBorder        = { fg = c.border, bg = c.bg_dim },
    BlinkCmpMenuSelection     = { bg = c.selection },
    BlinkCmpScrollBarThumb    = { bg = c.fg_dim },
    BlinkCmpScrollBarGutter   = { bg = c.bg_light },
    BlinkCmpLabel             = { fg = c.fg },
    BlinkCmpLabelDeprecated   = { fg = c.fg_dim, strikethrough = true },
    BlinkCmpLabelMatch        = { fg = c.yellow, bold = true },
    BlinkCmpLabelDetail       = { fg = c.fg_dim },
    BlinkCmpLabelDescription  = { fg = c.fg_dim },
    BlinkCmpKind              = { fg = c.teal, bg = c.bg_dim },
    BlinkCmpKindText          = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindMethod        = { fg = c.blue, bg = c.bg_dim },
    BlinkCmpKindFunction      = { fg = c.blue, bg = c.bg_dim },
    BlinkCmpKindConstructor   = { fg = c.blue, bg = c.bg_dim },
    BlinkCmpKindField         = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindVariable      = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindClass         = { fg = c.teal, bg = c.bg_dim },
    BlinkCmpKindInterface     = { fg = c.teal, bg = c.bg_dim },
    BlinkCmpKindModule        = { fg = c.teal, bg = c.bg_dim },
    BlinkCmpKindProperty      = { fg = c.yellow, bg = c.bg_dim },
    BlinkCmpKindKeyword       = { fg = c.violet, bg = c.bg_dim },
    BlinkCmpKindSnippet       = { fg = c.orange, bg = c.bg_dim },
    BlinkCmpKindColor         = { fg = c.yellow, bg = c.bg_dim },
    BlinkCmpKindFile          = { fg = c.blue, bg = c.bg_dim },
    BlinkCmpKindFolder        = { fg = c.blue, bg = c.bg_dim },
    BlinkCmpKindEnumMember    = { fg = c.yellow, bg = c.bg_dim },
    BlinkCmpKindConstant      = { fg = c.yellow, bg = c.bg_dim },
    BlinkCmpKindStruct        = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindTypeParameter = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindEnum          = { fg = c.yellow, bg = c.bg_dim },
    BlinkCmpKindOperator      = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindReference     = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpKindUnit          = { fg = c.orange, bg = c.bg_dim },
    BlinkCmpKindValue         = { fg = c.orange, bg = c.bg_dim },
    BlinkCmpKindEvent         = { fg = c.orange, bg = c.bg_dim },
    BlinkCmpDoc               = { fg = c.fg, bg = c.bg_dim },
    BlinkCmpDocBorder         = { fg = c.border, bg = c.bg_dim },
    BlinkCmpDocSeparator      = { fg = c.border },
    BlinkCmpDocCursorLine     = { bg = c.bg_light },
    BlinkCmpGhostText         = { fg = c.fg_dim, italic = true },
    BlinkCmpSource            = { fg = c.fg_dim },

    -- render-markdown.nvim
    RenderMarkdownH1          = { fg = c.yellow, bold = true },
    RenderMarkdownH2          = { fg = c.orange, bold = true },
    RenderMarkdownH3          = { fg = c.green, bold = true },
    RenderMarkdownH4          = { fg = c.teal, bold = true },
    RenderMarkdownH5          = { fg = c.blue, bold = true },
    RenderMarkdownH6          = { fg = c.violet, bold = true },
    RenderMarkdownH1Bg        = { bg = c.bg_light },
    RenderMarkdownH2Bg        = { bg = c.selection },
    RenderMarkdownH3Bg        = { bg = c.bg_light },
    RenderMarkdownH4Bg        = { bg = c.selection },
    RenderMarkdownH5Bg        = { bg = c.bg_light },
    RenderMarkdownH6Bg        = { bg = c.selection },
    RenderMarkdownCode        = { bg = c.bg_light },
    RenderMarkdownCodeInfo    = { fg = c.fg_dim, italic = true },
    RenderMarkdownCodeBorder  = { fg = c.border, bg = c.bg_light },
    RenderMarkdownCodeFallback = { fg = c.fg, bg = c.bg_light },
    RenderMarkdownCodeInline  = { fg = c.green, bg = c.bg_light },
    RenderMarkdownInlineHighlight = { fg = c.yellow, bg = c.bg_light, bold = true },
    RenderMarkdownQuote       = { fg = c.fg_dim, italic = true },
    RenderMarkdownQuote1      = { fg = c.yellow, italic = true },
    RenderMarkdownQuote2      = { fg = c.orange, italic = true },
    RenderMarkdownQuote3      = { fg = c.green, italic = true },
    RenderMarkdownQuote4      = { fg = c.teal, italic = true },
    RenderMarkdownQuote5      = { fg = c.blue, italic = true },
    RenderMarkdownQuote6      = { fg = c.violet, italic = true },
    RenderMarkdownBullet      = { fg = c.orange },
    RenderMarkdownDash        = { fg = c.fg_dim },
    RenderMarkdownSign        = { fg = c.fg_dim, bg = c.none },
    RenderMarkdownMath        = { fg = c.teal },
    RenderMarkdownIndent      = { fg = c.border },
    RenderMarkdownHtmlComment = { fg = c.fg_dim, italic = true },
    RenderMarkdownLink        = { fg = c.blue },
    RenderMarkdownLinkTitle   = { fg = c.teal, underline = true },
    RenderMarkdownWikiLink    = { fg = c.blue, underline = true },
    RenderMarkdownUnchecked   = { fg = c.fg_dim },
    RenderMarkdownChecked     = { fg = c.green, bold = true },
    RenderMarkdownTodo        = { fg = c.yellow, bold = true },
    RenderMarkdownTableHead   = { fg = c.yellow, bold = true },
    RenderMarkdownTableRow    = { fg = c.fg },
    RenderMarkdownSuccess     = { fg = c.green },
    RenderMarkdownInfo        = { fg = c.blue },
    RenderMarkdownHint        = { fg = c.teal },
    RenderMarkdownWarn        = { fg = c.orange },
    RenderMarkdownError       = { fg = c.red },
  }
end

return M
